spring:

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/full-stack-ecommerce?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:ecommerceapp}
    password: ${DB_PASSWORD:ecommerceapp}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    show-sql: true
    hibernate:
      ddl-auto: none

  application:
    name: ecommerce-webapp

  liquibase:
    change-log: classpath:/db/master-changelog.xml

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${APP_CONTEXT_PATH:/api/v1}

env:
  allowed:
    origins: ${ALLOWED_ORIGINS:http://localhost:4200}
#management:
#  endpoints:
#    web:
#      base-path: /actuator
#      exposure:
#        include: [ "health","prometheus", "metrics" ]
#  endpoint:
#    health:
#      show-details: always
#    metrics:
#      enabled: true
#    prometheus:
logging:
  level:
    org:
      springframework:
        web: DEBUG

#      enabled: true